"""fix_datetime_timezone

Revision ID: 2312f133cf2c
Revises: c82fb87e7a0d
Create Date: 2026-03-09 13:04:10.818660

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2312f133cf2c'
down_revision: str | None = 'c82fb87e7a0d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
