"""fix_datetime_timezone

Revision ID: c82fb87e7a0d
Revises: 831b8bc4e8ff
Create Date: 2026-03-09 13:03:29.437548

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c82fb87e7a0d'
down_revision: str | None = '831b8bc4e8ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
